name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    name: Go API - Test and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test ./...

      - name: Build
        run: go build -o server ./

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-server
          path: apps/api/server

  frontend:
    name: Web - Lint and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            apps/web/package-lock.json
            apps/web/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \
          elif [ -f package-lock.json ]; then npm ci; \
          else npm i; fi

      - name: Lint and typecheck
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm run lint && pnpm run build --no-lint; \
          else npm run build; fi

      - name: Upload Next artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-next
          path: |
            apps/web/.next
            apps/web/public

  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/one-password-api:latest

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/one-password-web:latest


